[build]
  publish = "dist"
  command = "npm run build"

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"
  generateForAllFiles = true

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    objectSrc = "'none'"
    scriptSrc = "'self' 'unsafe-hashes' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com"
    imgSrc = "'self' https://www.google-analytics.com"
    connectSrc = "'self' https://www.google-analytics.com"
    styleSrc = "'self' 'unsafe-hashes' fonts.googleapis.com"
    fontSrc = "'self' fonts.gstatic.com www.google-analytics.com"
    formAction = "'none'"


[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"