[build]
  publish = "dist"
  command = "npm run build"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; object-src 'none'; script-src 'self' www.google-analytics.com; style-src 'self' fonts.googleapis.com; img-src 'self' www.google-analytics.com; font-src 'self' fonts.gstatic.com www.google-analytics.com; connect-src 'self' www.google-analytics.com; form-action 'none';"