#!/bin/bash

# validate the jekyll project
if ! jekyll -v >/dev/null 2>&1; then
  cat >&2 <<HELP
Can not find jekyll
Ensure ruby is installed through your system's package manager and get jekyll through:

    bundle install
HELP
  exit 1;
else
  jekyll doctor
fi;

# validate the shell scripts
if ! shellcheck -V >/dev/null 2>&1; then
  cat >&2 <<HELP
Can not find ShellCheck. To validate the shell scripts please install it through your system's package manager.

See https://github.com/koalaman/shellcheck
HELP
  exit 1;
else
  shellcheck _scripts/*
fi;
